# MySQL.  Versions 4.1 and 5.0 are recommended.
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql
  encoding: utf8
  database: sword_development
  pool: 5
  username: root
  password: 
  host: localhost
  #Make sure the local firewall software (e.g. Avira, SpamKiller pro or other stuff) does not block the ports generally. then use port 3306.

test:
  adapter: mysql
  encoding: utf8
  database: sword_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: sword_production
  pool: 5
  username: root
  password:
  host: localhost

